-- ==============================================================================
-- SENINFLUENCEURS — Supabase SQL Schema (jvkrryakllbxplsynwpt)
-- Exécutez ce script dans l'éditeur SQL de votre tableau de bord Supabase
-- ==============================================================================

-- 1. Table des Influenceurs et Créateurs de Contenu
CREATE TABLE IF NOT EXISTS public.influencers (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Micro-influenceur', -- 'Macro-influenceur' | 'Micro-influenceur'
    niche TEXT NOT NULL DEFAULT 'Lifestyle',
    followers TEXT NOT NULL DEFAULT '100K',
    followers_count INTEGER NOT NULL DEFAULT 100000,
    photo TEXT NOT NULL,
    verified BOOLEAN DEFAULT true,
    featured BOOLEAN DEFAULT false,
    engagement_rate TEXT DEFAULT '8.0%',
    bio TEXT,
    socials JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index pour recherche rapide
CREATE INDEX IF NOT EXISTS idx_influencers_category ON public.influencers(category);
CREATE INDEX IF NOT EXISTS idx_influencers_niche ON public.influencers(niche);
CREATE INDEX IF NOT EXISTS idx_influencers_followers ON public.influencers(followers_count DESC);

-- 2. Table des Contacts & Demandes de Campagnes (Briefs)
CREATE TABLE IF NOT EXISTS public.contacts (
    id BIGSERIAL PRIMARY KEY,
    company_name TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    budget TEXT,
    objective TEXT,
    talent_type TEXT,
    message TEXT NOT NULL,
    file_name TEXT,
    status TEXT DEFAULT 'nouveau', -- 'nouveau' | 'en_cours' | 'traite'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table des Articles & Actualités
CREATE TABLE IF NOT EXISTS public.articles (
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT,
    content TEXT NOT NULL,
    category TEXT,
    read_time TEXT DEFAULT '5 min',
    image TEXT,
    published BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Activer Row Level Security (RLS)
ALTER TABLE public.influencers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Politiques RLS : Lecture publique de tous les influenceurs et articles
CREATE POLICY "Lecture publique influenceurs" ON public.influencers
    FOR SELECT USING (true);

CREATE POLICY "Insertion publique influenceurs" ON public.influencers
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Mise à jour influenceurs" ON public.influencers
    FOR UPDATE USING (true);

CREATE POLICY "Suppression influenceurs" ON public.influencers
    FOR DELETE USING (true);

CREATE POLICY "Lecture publique articles" ON public.articles
    FOR SELECT USING (true);

-- Politiques RLS pour les formulaires de contact
CREATE POLICY "Envoi de brief public" ON public.contacts
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Consultation des briefs" ON public.contacts
    FOR SELECT USING (true);

-- ==============================================================================
-- Bravo ! Votre base de données SENINFLUENCEURS est prête.
-- ==============================================================================

-- ==============================================================================
-- SEED DATA — 180+ INFLUENCEURS DU SÉNÉGAL (DONT 155 MACRO-INFLUENCEURS OFFICIELS)
-- ==============================================================================

-- Vider avant réinsertion si nécessaire
-- TRUNCATE TABLE public.influencers RESTART IDENTITY CASCADE;

INSERT INTO public.influencers (id, name, category, niche, followers, followers_count, photo, verified, featured, engagement_rate, bio, socials)
VALUES
  (172, 'Diodio Glow Skin', 'Macro-influenceur', 'Mode & Beauté', '1.2M', 1200000, 'https://res.cloudinary.com/dwp4isflu/image/upload/v1791242605/portfolio-172_iwk9uo.webp', true, true, '7.8%', 'Créatrice de contenu bien-être, soins de la peau et cosmétique naturelle. Référence beauté et glow lifestyle au Sénégal et en Afrique de l''Ouest.', '{"tiktok":"https://tiktok.com/@diodioglowskin","instagram":"https://instagram.com/diodioglowskin","youtube":"https://youtube.com/@diodioglowskin","facebook":"https://facebook.com"}'::jsonb),
  (170, 'PA ASSANE GUEYE', 'Macro-influenceur', 'Humour & Comédie', '1.9M', 1900000, 'https://res.cloudinary.com/dwp4isflu/image/upload/v1791242604/portfolio-170_gf6jlf.webp', true, true, '9.4%', 'Comédien et créateur de sketchs humoristiques viraux sur TikTok et Facebook. Des millions de vues à travers la diaspora africaine et le Sénégal.', '{"tiktok":"https://tiktok.com/@paassanegueye","instagram":"https://instagram.com/paassanegueye","facebook":"https://facebook.com"}'::jsonb),
  (168, 'Omar Africa', 'Macro-influenceur', 'Lifestyle & Culture', '1.4M', 1400000, 'https://res.cloudinary.com/dwp4isflu/image/upload/v1791242604/portfolio-168_me9mc5.webp', true, true, '8.1%', 'Ambassadeur de la culture urbaine africaine, créateur digital, street-style et voyages à travers le continent.', '{"tiktok":"https://tiktok.com/@omarafrica","instagram":"https://instagram.com/omarafrica","youtube":"https://youtube.com/@omarafrica"}'::jsonb),
  (61, 'Princess_rouge', 'Macro-influenceur', 'Mode & Beauté', '590K', 590000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, true, '10.1%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@princess_rouge","instagram":"https://instagram.com/princess_rouge","facebook":"https://facebook.com"}'::jsonb),
  (64, 'El hadji omar ba', 'Macro-influenceur', 'Musique & Danse', '1.9M', 1900000, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Talent rythmé et créateur(trice) de vibes afro-urbaines incontournables. Rythme les tendances musicales et les challenges viraux sur TikTok et Instagram.', '{"tiktok":"https://tiktok.com/@elhadjiomarba","instagram":"https://instagram.com/elhadjiomarba","facebook":"https://facebook.com","youtube":"https://youtube.com/@elhadjiomarba"}'::jsonb),
  (70, 'Nafi sen petit galle', 'Macro-influenceur', 'Médias & Animateurs', '860K', 860000, 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&auto=format&fit=crop&q=80', true, true, '7.7%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@nafisenpetitgalle","instagram":"https://instagram.com/nafisenpetitgalle","facebook":"https://facebook.com"}'::jsonb),
  (71, 'Adaa_bellefleur', 'Macro-influenceur', 'Mode & Beauté', '750K', 750000, 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=600&auto=format&fit=crop&q=80', true, true, '9.5%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@adaa_bellefleur","instagram":"https://instagram.com/adaa_bellefleur","facebook":"https://facebook.com"}'::jsonb),
  (72, 'Mouhamed Niang', 'Macro-influenceur', 'Humour & Comédie', '640K', 640000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, true, '7.4%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@mouhamedniang","instagram":"https://instagram.com/mouhamedniang","facebook":"https://facebook.com"}'::jsonb),
  (91, 'Aliana', 'Macro-influenceur', 'Humour & Comédie', '2.4M', 2400000, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80', true, true, '9.8%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@aliana","instagram":"https://instagram.com/aliana","facebook":"https://facebook.com","youtube":"https://youtube.com/@aliana"}'::jsonb),
  (92, 'Helenita', 'Macro-influenceur', 'Médias & Animateurs', '1.6M', 1600000, 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&auto=format&fit=crop&q=80', true, true, '11.2%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@helenita","instagram":"https://instagram.com/helenita","facebook":"https://facebook.com","youtube":"https://youtube.com/@helenita"}'::jsonb),
  (93, 'Aissatou Loum', 'Macro-influenceur', 'Humour & Comédie', '1.2M', 1200000, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80', true, true, '9.1%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@aissatouloum","instagram":"https://instagram.com/aissatouloum","facebook":"https://facebook.com","youtube":"https://youtube.com/@aissatouloum"}'::jsonb),
  (103, 'COACH PROFAIT', 'Macro-influenceur', 'Business & Éducation', '520K', 520000, 'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=600&auto=format&fit=crop&q=80', true, true, '7.6%', 'Leader d''opinion et créateur(trice) de contenus inspirants alliant expertise, développement personnel et vision entrepreneuriale pour la jeunesse sénégalaise.', '{"tiktok":"https://tiktok.com/@coachprofait","instagram":"https://instagram.com/coachprofait","facebook":"https://facebook.com"}'::jsonb),
  (110, 'M_BAYES', 'Macro-influenceur', 'Médias & Animateurs', '920K', 920000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, true, '10.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@m_bayes","instagram":"https://instagram.com/m_bayes","facebook":"https://facebook.com"}'::jsonb),
  (112, 'YATMA PROD', 'Macro-influenceur', 'Médias & Animateurs', '750K', 750000, 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80', true, true, '9.5%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@yatmaprod","instagram":"https://instagram.com/yatmaprod","facebook":"https://facebook.com"}'::jsonb),
  (114, 'MYA BLACKY', 'Macro-influenceur', 'Mode & Beauté', '590K', 590000, 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&auto=format&fit=crop&q=80', true, true, '10.1%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@myablacky","instagram":"https://instagram.com/myablacky","facebook":"https://facebook.com"}'::jsonb),
  (116, 'KHADY DIAKHATE', 'Macro-influenceur', 'Mode & Beauté', '2.4M', 2400000, 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80', true, true, '9.8%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@khadydiakhate","instagram":"https://instagram.com/khadydiakhate","facebook":"https://facebook.com","youtube":"https://youtube.com/@khadydiakhate"}'::jsonb),
  (117, 'REMAINS BLACK WOMAN', 'Macro-influenceur', 'Mode & Beauté', '1.6M', 1600000, 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80', true, true, '11.2%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@remainsblackwoman","instagram":"https://instagram.com/remainsblackwoman","facebook":"https://facebook.com","youtube":"https://youtube.com/@remainsblackwoman"}'::jsonb),
  (123, 'LISSA CHANNEL', 'Macro-influenceur', 'Médias & Animateurs', '810K', 810000, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@lissachannel","instagram":"https://instagram.com/lissachannel","facebook":"https://facebook.com"}'::jsonb),
  (124, 'MAMAN NORA MBENGUE', 'Macro-influenceur', 'Lifestyle & Culture', '690K', 690000, 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@mamannorambengue","instagram":"https://instagram.com/mamannorambengue","facebook":"https://facebook.com"}'::jsonb),
  (125, 'ABOUBKJ_OFFICIEL', 'Macro-influenceur', 'Lifestyle & Culture', '590K', 590000, 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Créateur(trice) de contenus de référence (Hello), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@aboubkj_officiel","instagram":"https://instagram.com/aboubkj_officiel","facebook":"https://facebook.com"}'::jsonb),
  (130, 'MC CANA', 'Macro-influenceur', 'Lifestyle & Culture', '1.4M', 1400000, 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@mccana","instagram":"https://instagram.com/mccana","facebook":"https://facebook.com","youtube":"https://youtube.com/@mccana"}'::jsonb),
  (131, 'KINE KINE L’OFFICIEL', 'Macro-influenceur', 'Lifestyle & Culture', '1.1M', 1100000, 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@kinekinelofficiel","instagram":"https://instagram.com/kinekinelofficiel","facebook":"https://facebook.com","youtube":"https://youtube.com/@kinekinelofficiel"}'::jsonb),
  (132, 'KHADIJA DOUMBIA', 'Macro-influenceur', 'Lifestyle & Culture', '920K', 920000, 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@khadijadoumbia","instagram":"https://instagram.com/khadijadoumbia","facebook":"https://facebook.com"}'::jsonb),
  (133, 'MARIAMA OFFICIEL', 'Macro-influenceur', 'Lifestyle & Culture', '810K', 810000, 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@mariamaofficiel","instagram":"https://instagram.com/mariamaofficiel","facebook":"https://facebook.com"}'::jsonb),
  (134, 'ROKHAYA RASSOUL', 'Macro-influenceur', 'Mode & Beauté', '690K', 690000, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@rokhayarassoul","instagram":"https://instagram.com/rokhayarassoul","facebook":"https://facebook.com"}'::jsonb),
  (135, 'DJ MOMO20', 'Macro-influenceur', 'Musique & Danse', '590K', 590000, 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Talent rythmé et créateur(trice) de vibes afro-urbaines incontournables. Rythme les tendances musicales et les challenges viraux sur TikTok et Instagram.', '{"tiktok":"https://tiktok.com/@djmomo20","instagram":"https://instagram.com/djmomo20","facebook":"https://facebook.com"}'::jsonb),
  (136, 'MOI C’EST FATIMA', 'Macro-influenceur', 'Mode & Beauté', '520K', 520000, 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@moicestfatima","instagram":"https://instagram.com/moicestfatima","facebook":"https://facebook.com"}'::jsonb),
  (137, 'MARIE IDILIA', 'Macro-influenceur', 'Humour & Comédie', '1.9M', 1900000, 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@marieidilia","instagram":"https://instagram.com/marieidilia","facebook":"https://facebook.com","youtube":"https://youtube.com/@marieidilia"}'::jsonb),
  (140, 'SHASHA_SOW', 'Macro-influenceur', 'Humour & Comédie', '1.1M', 1100000, 'https://images.unsplash.com/photo-1507152832244-10d45c7eda57?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@shasha_sow","instagram":"https://instagram.com/shasha_sow","facebook":"https://facebook.com","youtube":"https://youtube.com/@shasha_sow"}'::jsonb),
  (141, 'GAB''S', 'Macro-influenceur', 'Lifestyle & Culture', '920K', 920000, 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Créateur(trice) de contenus de référence (Createur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@gabs","instagram":"https://instagram.com/gabs","facebook":"https://facebook.com"}'::jsonb),
  (142, 'BK MU SALIOU NIANG', 'Macro-influenceur', 'Mode & Beauté', '810K', 810000, 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@bkmusaliouniang","instagram":"https://instagram.com/bkmusaliouniang","facebook":"https://facebook.com"}'::jsonb),
  (145, 'PAPY MCAE', 'Macro-influenceur', 'Humour & Comédie', '590K', 590000, 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@papymcae","instagram":"https://instagram.com/papymcae","facebook":"https://facebook.com"}'::jsonb),
  (147, 'MANIANG REUS', 'Macro-influenceur', 'Humour & Comédie', '2.4M', 2400000, 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600&auto=format&fit=crop&q=80', true, true, '9.8%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@maniangreus","instagram":"https://instagram.com/maniangreus","facebook":"https://facebook.com","youtube":"https://youtube.com/@maniangreus"}'::jsonb),
  (148, 'GUEYE NO STRESS', 'Macro-influenceur', 'Humour & Comédie', '1.6M', 1600000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, true, '11.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@gueyenostress","instagram":"https://instagram.com/gueyenostress","facebook":"https://facebook.com","youtube":"https://youtube.com/@gueyenostress"}'::jsonb),
  (149, 'PETITE BAMBARAH', 'Macro-influenceur', 'Lifestyle & Culture', '1.2M', 1200000, 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80', true, true, '9.1%', 'Créateur(trice) de contenus de référence (créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@petitebambarah","instagram":"https://instagram.com/petitebambarah","facebook":"https://facebook.com","youtube":"https://youtube.com/@petitebambarah"}'::jsonb),
  (150, 'LIESA', 'Macro-influenceur', 'Mode & Beauté', '980K', 980000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '8.6%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@liesa","instagram":"https://instagram.com/liesa","facebook":"https://facebook.com"}'::jsonb),
  (152, 'RIIMAA', 'Macro-influenceur', 'Musique & Danse', '810K', 810000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Talent rythmé et créateur(trice) de vibes afro-urbaines incontournables. Rythme les tendances musicales et les challenges viraux sur TikTok et Instagram.', '{"tiktok":"https://tiktok.com/@riimaa","instagram":"https://instagram.com/riimaa","facebook":"https://facebook.com"}'::jsonb),
  (154, 'SYLLA HUMORISTE', 'Macro-influenceur', 'Médias & Animateurs', '640K', 640000, 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=80', true, false, '7.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@syllahumoriste","instagram":"https://instagram.com/syllahumoriste","facebook":"https://facebook.com"}'::jsonb),
  (155, 'BM BOY', 'Macro-influenceur', 'Lifestyle & Culture', '540K', 540000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '8.3%', 'Créateur(trice) de contenus de référence (créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@bmboy","instagram":"https://instagram.com/bmboy","facebook":"https://facebook.com"}'::jsonb),
  (157, 'GAYE HASSANENARROUGOOR', 'Macro-influenceur', 'Humour & Comédie', '1.9M', 1900000, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@gayehassanenarrougoor","instagram":"https://instagram.com/gayehassanenarrougoor","facebook":"https://facebook.com","youtube":"https://youtube.com/@gayehassanenarrougoor"}'::jsonb),
  (159, 'DIOP NO STRESS', 'Macro-influenceur', 'Humour & Comédie', '1.2M', 1200000, 'https://res.cloudinary.com/dwp4isflu/image/upload/v1780920710/portfolio-159_x6n0rm.jpg', true, true, '9.1%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@diopnostress","instagram":"https://instagram.com/diopnostress","facebook":"https://facebook.com","youtube":"https://youtube.com/@diopnostress"}'::jsonb),
  (160, 'PEUZZI MONTANA', 'Macro-influenceur', 'Médias & Animateurs', '980K', 980000, 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=600&auto=format&fit=crop&q=80', true, false, '8.6%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@peuzzimontana","instagram":"https://instagram.com/peuzzimontana","facebook":"https://facebook.com"}'::jsonb),
  (161, 'AZIZ DIAGOLA', 'Macro-influenceur', 'Lifestyle & Culture', '860K', 860000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, false, '7.7%', 'Créateur(trice) de contenus de référence (créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@azizdiagola","instagram":"https://instagram.com/azizdiagola","facebook":"https://facebook.com"}'::jsonb),
  (162, 'BINETTE AND MOUSSA', 'Macro-influenceur', 'Humour & Comédie', '750K', 750000, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80', true, false, '9.5%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@binetteandmoussa","instagram":"https://instagram.com/binetteandmoussa","facebook":"https://facebook.com"}'::jsonb),
  (163, 'NAGUM _ NUGUM', 'Macro-influenceur', 'Lifestyle & Culture', '640K', 640000, 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&auto=format&fit=crop&q=80', true, false, '7.4%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@nagum_nugum","instagram":"https://instagram.com/nagum_nugum","facebook":"https://facebook.com"}'::jsonb),
  (165, 'JUMELLE DIARRA', 'Macro-influenceur', 'Médias & Animateurs', '520K', 520000, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@jumellediarra","instagram":"https://instagram.com/jumellediarra","facebook":"https://facebook.com"}'::jsonb),
  (166, 'MEDMOH SOURIRE', 'Macro-influenceur', 'Humour & Comédie', '1.9M', 1900000, 'https://res.cloudinary.com/dwp4isflu/image/upload/v1780920733/portfolio-166_sdx2hl.jpg', true, true, '8.9%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@medmohsourire","instagram":"https://instagram.com/medmohsourire","facebook":"https://facebook.com","youtube":"https://youtube.com/@medmohsourire"}'::jsonb),
  (167, 'CHAMANEH GUEYE', 'Macro-influenceur', 'Médias & Animateurs', '1.4M', 1400000, 'https://res.cloudinary.com/dwp4isflu/image/upload/v1780920737/portfolio-167_cigtnz.jpg', true, true, '8.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@chamanehgueye","instagram":"https://instagram.com/chamanehgueye","facebook":"https://facebook.com","youtube":"https://youtube.com/@chamanehgueye"}'::jsonb),
  (169, 'AISSA TOUT FAYE', 'Macro-influenceur', 'Mode & Beauté', '980K', 980000, 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80', true, false, '8.6%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@aissatoutfaye","instagram":"https://instagram.com/aissatoutfaye","facebook":"https://facebook.com"}'::jsonb),
  (171, 'DAVID BLACK', 'Macro-influenceur', 'Mode & Beauté', '810K', 810000, 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@davidblack","instagram":"https://instagram.com/davidblack","facebook":"https://facebook.com"}'::jsonb),
  (173, 'OMAR TV', 'Macro-influenceur', 'Médias & Animateurs', '640K', 640000, 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80', true, false, '7.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@omartv","instagram":"https://instagram.com/omartv","facebook":"https://facebook.com"}'::jsonb),
  (174, 'Fatima Cissé', 'Macro-influenceur', 'Mode & Beauté', '540K', 540000, 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80', true, false, '8.3%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@fatimacisse","instagram":"https://instagram.com/fatimacisse","facebook":"https://facebook.com"}'::jsonb),
  (175, 'ndeye_ndack4', 'Macro-influenceur', 'Lifestyle & Culture', '2.4M', 2400000, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80', true, true, '9.8%', 'Créateur(trice) de contenus de référence (créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@ndeye_ndack4","instagram":"https://instagram.com/ndeye_ndack4","facebook":"https://facebook.com","youtube":"https://youtube.com/@ndeye_ndack4"}'::jsonb),
  (176, 'MET MAQUETTE', 'Macro-influenceur', 'Business & Éducation', '1.6M', 1600000, 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&auto=format&fit=crop&q=80', true, true, '11.2%', 'Leader d''opinion et créateur(trice) de contenus inspirants alliant expertise, développement personnel et vision entrepreneuriale pour la jeunesse sénégalaise.', '{"tiktok":"https://tiktok.com/@metmaquette","instagram":"https://instagram.com/metmaquette","facebook":"https://facebook.com","youtube":"https://youtube.com/@metmaquette"}'::jsonb),
  (178, 'AJA SOOW', 'Macro-influenceur', 'Humour & Comédie', '1.1M', 1100000, 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@ajasoow","instagram":"https://instagram.com/ajasoow","facebook":"https://facebook.com","youtube":"https://youtube.com/@ajasoow"}'::jsonb),
  (180, 'Édouardo', 'Macro-influenceur', 'Médias & Animateurs', '860K', 860000, 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=80', true, false, '7.7%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@edouardo","instagram":"https://instagram.com/edouardo","facebook":"https://facebook.com"}'::jsonb),
  (183, 'RASS NK', 'Macro-influenceur', 'Mode & Beauté', '640K', 640000, 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80', true, false, '7.4%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@rassnk","instagram":"https://instagram.com/rassnk","facebook":"https://facebook.com"}'::jsonb),
  (186, 'LOULOU OFF', 'Macro-influenceur', 'Lifestyle & Culture', '2.4M', 2400000, 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80', true, true, '9.8%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@loulouoff","instagram":"https://instagram.com/loulouoff","facebook":"https://facebook.com","youtube":"https://youtube.com/@loulouoff"}'::jsonb),
  (188, 'SAMUELLA KOUASSI', 'Macro-influenceur', 'Médias & Animateurs', '1.4M', 1400000, 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@samuellakouassi","instagram":"https://instagram.com/samuellakouassi","facebook":"https://facebook.com","youtube":"https://youtube.com/@samuellakouassi"}'::jsonb),
  (189, 'AMY DABO', 'Macro-influenceur', 'Humour & Comédie', '1.1M', 1100000, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@amydabo","instagram":"https://instagram.com/amydabo","facebook":"https://facebook.com","youtube":"https://youtube.com/@amydabo"}'::jsonb),
  (190, 'ANITAH & BAMBA', 'Macro-influenceur', 'Lifestyle & Culture', '920K', 920000, 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@anitahbamba","instagram":"https://instagram.com/anitahbamba","facebook":"https://facebook.com"}'::jsonb),
  (191, 'RACH MAKOSSO', 'Macro-influenceur', 'Humour & Comédie', '810K', 810000, 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@rachmakosso","instagram":"https://instagram.com/rachmakosso","facebook":"https://facebook.com"}'::jsonb),
  (192, 'DJIBY SEYE', 'Macro-influenceur', 'Humour & Comédie', '690K', 690000, 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@djibyseye","instagram":"https://instagram.com/djibyseye","facebook":"https://facebook.com"}'::jsonb),
  (193, 'The Real Yayoud', 'Macro-influenceur', 'Médias & Animateurs', '590K', 590000, 'https://images.unsplash.com/photo-1507152832244-10d45c7eda57?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@therealyayoud","instagram":"https://instagram.com/therealyayoud","facebook":"https://facebook.com"}'::jsonb),
  (194, 'NANAH FALL', 'Macro-influenceur', 'Lifestyle & Culture', '520K', 520000, 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@nanahfall","instagram":"https://instagram.com/nanahfall","facebook":"https://facebook.com"}'::jsonb),
  (195, 'RACKY KUSH', 'Macro-influenceur', 'Mode & Beauté', '1.9M', 1900000, 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@rackykush","instagram":"https://instagram.com/rackykush","facebook":"https://facebook.com","youtube":"https://youtube.com/@rackykush"}'::jsonb),
  (198, 'KYA SERIE MUNIEUL', 'Macro-influenceur', 'Cinéma & Séries', '1.1M', 1100000, 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Artiste et comédien(ne) d''exception, figure majeure du paysage audiovisuel et des séries phares sénégalaises. Très apprécié(e) pour son jeu d''acteur et sa forte proximité avec le public.', '{"tiktok":"https://tiktok.com/@kyaseriemunieul","instagram":"https://instagram.com/kyaseriemunieul","facebook":"https://facebook.com","youtube":"https://youtube.com/@kyaseriemunieul"}'::jsonb),
  (199, 'AWA MACINA', 'Macro-influenceur', 'Médias & Animateurs', '920K', 920000, 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@awamacina","instagram":"https://instagram.com/awamacina","facebook":"https://facebook.com"}'::jsonb),
  (200, 'AMINA SALL', 'Macro-influenceur', 'Humour & Comédie', '810K', 810000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@aminasall","instagram":"https://instagram.com/aminasall","facebook":"https://facebook.com"}'::jsonb),
  (202, 'ZAHRA AIDARA', 'Macro-influenceur', 'Médias & Animateurs', '640K', 640000, 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80', true, false, '7.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@zahraaidara","instagram":"https://instagram.com/zahraaidara","facebook":"https://facebook.com"}'::jsonb),
  (203, 'PITTOLA', 'Macro-influenceur', 'Lifestyle & Culture', '540K', 540000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '8.3%', 'Créateur(trice) de contenus de référence (créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@pittola","instagram":"https://instagram.com/pittola","facebook":"https://facebook.com"}'::jsonb),
  (204, 'GALSEN PEOPLE', 'Macro-influenceur', 'Médias & Animateurs', '2.4M', 2400000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, true, '9.8%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@galsenpeople","instagram":"https://instagram.com/galsenpeople","facebook":"https://facebook.com","youtube":"https://youtube.com/@galsenpeople"}'::jsonb),
  (205, 'NDEYA RASSOUL', 'Macro-influenceur', 'Cinéma & Séries', '1.6M', 1600000, 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=80', true, true, '11.2%', 'Artiste et comédien(ne) d''exception, figure majeure du paysage audiovisuel et des séries phares sénégalaises. Très apprécié(e) pour son jeu d''acteur et sa forte proximité avec le public.', '{"tiktok":"https://tiktok.com/@ndeyarassoul","instagram":"https://instagram.com/ndeyarassoul","facebook":"https://facebook.com","youtube":"https://youtube.com/@ndeyarassoul"}'::jsonb),
  (206, 'KHAADIA SY', 'Macro-influenceur', 'Médias & Animateurs', '1.2M', 1200000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, true, '9.1%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@khaadiasy","instagram":"https://instagram.com/khaadiasy","facebook":"https://facebook.com","youtube":"https://youtube.com/@khaadiasy"}'::jsonb),
  (207, 'MALICK LINK', 'Macro-influenceur', 'Humour & Comédie', '980K', 980000, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80', true, false, '8.6%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@malicklink","instagram":"https://instagram.com/malicklink","facebook":"https://facebook.com"}'::jsonb),
  (208, 'Belledior_officielle', 'Macro-influenceur', 'Mode & Beauté', '860K', 860000, 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&auto=format&fit=crop&q=80', true, false, '7.7%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@belledior_officielle","instagram":"https://instagram.com/belledior_officielle","facebook":"https://facebook.com"}'::jsonb),
  (209, 'SANKIS', 'Macro-influenceur', 'Lifestyle & Culture', '750K', 750000, 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=600&auto=format&fit=crop&q=80', true, false, '9.5%', 'Créateur(trice) de contenus de référence (créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@sankis","instagram":"https://instagram.com/sankis","facebook":"https://facebook.com"}'::jsonb),
  (213, 'MARIAMA KAMARA', 'Macro-influenceur', 'Mode & Beauté', '520K', 520000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@mariamakamara","instagram":"https://instagram.com/mariamakamara","facebook":"https://facebook.com"}'::jsonb),
  (214, 'LENA HABIB', 'Macro-influenceur', 'Mode & Beauté', '1.9M', 1900000, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@lenahabib","instagram":"https://instagram.com/lenahabib","facebook":"https://facebook.com","youtube":"https://youtube.com/@lenahabib"}'::jsonb),
  (215, 'MAODO MALICK MBAYE', 'Macro-influenceur', 'Humour & Comédie', '1.4M', 1400000, 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@maodomalickmbaye","instagram":"https://instagram.com/maodomalickmbaye","facebook":"https://facebook.com","youtube":"https://youtube.com/@maodomalickmbaye"}'::jsonb),
  (218, 'BAE VNTA', 'Macro-influenceur', 'Humour & Comédie', '920K', 920000, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@baevnta","instagram":"https://instagram.com/baevnta","facebook":"https://facebook.com"}'::jsonb),
  (219, 'DUDU FARAMARENE', 'Macro-influenceur', 'Humour & Comédie', '810K', 810000, 'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@dudufaramarene","instagram":"https://instagram.com/dudufaramarene","facebook":"https://facebook.com"}'::jsonb),
  (220, 'BADOU SYLLA', 'Macro-influenceur', 'Médias & Animateurs', '690K', 690000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@badousylla","instagram":"https://instagram.com/badousylla","facebook":"https://facebook.com"}'::jsonb),
  (221, 'KIRA DIOP', 'Macro-influenceur', 'Lifestyle & Culture', '590K', 590000, 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Créateur(trice) de contenus de référence (créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@kiradiop","instagram":"https://instagram.com/kiradiop","facebook":"https://facebook.com"}'::jsonb),
  (222, 'iam_awathies', 'Macro-influenceur', 'Humour & Comédie', '520K', 520000, 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@iam_awathies","instagram":"https://instagram.com/iam_awathies","facebook":"https://facebook.com"}'::jsonb),
  (223, 'Papeuh Dame', 'Macro-influenceur', 'Lifestyle & Culture', '1.9M', 1900000, 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Créateur(trice) de contenus de référence (créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@papeuhdame","instagram":"https://instagram.com/papeuhdame","facebook":"https://facebook.com","youtube":"https://youtube.com/@papeuhdame"}'::jsonb),
  (224, 'zeyna_bamba_ndiaye', 'Macro-influenceur', 'Médias & Animateurs', '1.4M', 1400000, 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@zeyna_bamba_ndiaye","instagram":"https://instagram.com/zeyna_bamba_ndiaye","facebook":"https://facebook.com","youtube":"https://youtube.com/@zeyna_bamba_ndiaye"}'::jsonb),
  (225, 'diossa_ak_diarbat', 'Macro-influenceur', 'Médias & Animateurs', '1.1M', 1100000, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@diossa_ak_diarbat","instagram":"https://instagram.com/diossa_ak_diarbat","facebook":"https://facebook.com","youtube":"https://youtube.com/@diossa_ak_diarbat"}'::jsonb),
  (226, 'PAPA ET SES VIDÉOS', 'Macro-influenceur', 'Lifestyle & Culture', '920K', 920000, 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@papaetsesvideos","instagram":"https://instagram.com/papaetsesvideos","facebook":"https://facebook.com"}'::jsonb),
  (227, 'MATY KEYS', 'Macro-influenceur', 'Humour & Comédie', '810K', 810000, 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@matykeys","instagram":"https://instagram.com/matykeys","facebook":"https://facebook.com"}'::jsonb),
  (228, 'Jamal Nadir', 'Macro-influenceur', 'Lifestyle & Culture', '690K', 690000, 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@jamalnadir","instagram":"https://instagram.com/jamalnadir","facebook":"https://facebook.com"}'::jsonb),
  (229, 'BOY MARHONE', 'Macro-influenceur', 'Lifestyle & Culture', '590K', 590000, 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Créateur(trice) de contenus de référence (créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@boymarhone","instagram":"https://instagram.com/boymarhone","facebook":"https://facebook.com"}'::jsonb),
  (230, 'Alassane Bah', 'Macro-influenceur', 'Lifestyle & Culture', '520K', 520000, 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Créateur(trice) de contenus de référence (créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@alassanebah","instagram":"https://instagram.com/alassanebah","facebook":"https://facebook.com"}'::jsonb),
  (231, 'Muha Diagne', 'Macro-influenceur', 'Mode & Beauté', '1.9M', 1900000, 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@muhadiagne","instagram":"https://instagram.com/muhadiagne","facebook":"https://facebook.com","youtube":"https://youtube.com/@muhadiagne"}'::jsonb),
  (232, 'Negre Raffiné', 'Macro-influenceur', 'Humour & Comédie', '1.4M', 1400000, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@negreraffine","instagram":"https://instagram.com/negreraffine","facebook":"https://facebook.com","youtube":"https://youtube.com/@negreraffine"}'::jsonb),
  (233, 'Médecin Conscient', 'Macro-influenceur', 'Business & Éducation', '1.1M', 1100000, 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Leader d''opinion et créateur(trice) de contenus inspirants alliant expertise, développement personnel et vision entrepreneuriale pour la jeunesse sénégalaise.', '{"tiktok":"https://tiktok.com/@medecinconscient","instagram":"https://instagram.com/medecinconscient","facebook":"https://facebook.com","youtube":"https://youtube.com/@medecinconscient"}'::jsonb),
  (234, 'Maman Africa', 'Macro-influenceur', 'Lifestyle & Culture', '920K', 920000, 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@mamanafrica","instagram":"https://instagram.com/mamanafrica","facebook":"https://facebook.com"}'::jsonb),
  (235, 'Mame Bousso', 'Macro-influenceur', 'Lifestyle & Culture', '810K', 810000, 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@mamebousso","instagram":"https://instagram.com/mamebousso","facebook":"https://facebook.com"}'::jsonb),
  (236, 'Chumo', 'Macro-influenceur', 'Médias & Animateurs', '690K', 690000, 'https://images.unsplash.com/photo-1507152832244-10d45c7eda57?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@chumo","instagram":"https://instagram.com/chumo","facebook":"https://facebook.com"}'::jsonb),
  (237, 'Bb codou', 'Macro-influenceur', 'Mode & Beauté', '590K', 590000, 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@bbcodou","instagram":"https://instagram.com/bbcodou","facebook":"https://facebook.com"}'::jsonb),
  (238, 'MRS MATADI', 'Macro-influenceur', 'Lifestyle & Culture', '520K', 520000, 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@mrsmatadi","instagram":"https://instagram.com/mrsmatadi","facebook":"https://facebook.com"}'::jsonb),
  (239, 'Eva Rvss', 'Macro-influenceur', 'Lifestyle & Culture', '1.9M', 1900000, 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Créateur(trice) de contenus de référence (Créatrice contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@evarvss","instagram":"https://instagram.com/evarvss","facebook":"https://facebook.com","youtube":"https://youtube.com/@evarvss"}'::jsonb),
  (240, 'Agrolabdecouvre', 'Macro-influenceur', 'Business & Éducation', '1.4M', 1400000, 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Leader d''opinion et créateur(trice) de contenus inspirants alliant expertise, développement personnel et vision entrepreneuriale pour la jeunesse sénégalaise.', '{"tiktok":"https://tiktok.com/@agrolabdecouvre","instagram":"https://instagram.com/agrolabdecouvre","facebook":"https://facebook.com","youtube":"https://youtube.com/@agrolabdecouvre"}'::jsonb),
  (241, 'Princesse Ndiaye', 'Macro-influenceur', 'Lifestyle & Culture', '1.1M', 1100000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@princessendiaye","instagram":"https://instagram.com/princessendiaye","facebook":"https://facebook.com","youtube":"https://youtube.com/@princessendiaye"}'::jsonb),
  (242, 'Amna Business', 'Macro-influenceur', 'Business & Éducation', '920K', 920000, 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Leader d''opinion et créateur(trice) de contenus inspirants alliant expertise, développement personnel et vision entrepreneuriale pour la jeunesse sénégalaise.', '{"tiktok":"https://tiktok.com/@amnabusiness","instagram":"https://instagram.com/amnabusiness","facebook":"https://facebook.com"}'::jsonb),
  (243, 'Falilouh IJ', 'Macro-influenceur', 'Humour & Comédie', '810K', 810000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@falilouhij","instagram":"https://instagram.com/falilouhij","facebook":"https://facebook.com"}'::jsonb),
  (244, 'Ken Sama', 'Macro-influenceur', 'Humour & Comédie', '690K', 690000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@kensama","instagram":"https://instagram.com/kensama","facebook":"https://facebook.com"}'::jsonb),
  (252, 'Ndeye NDIAYE', 'Macro-influenceur', 'Lifestyle & Culture', '1.2M', 1200000, 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=80', true, true, '9.1%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@ndeyendiaye","instagram":"https://instagram.com/ndeyendiaye","facebook":"https://facebook.com","youtube":"https://youtube.com/@ndeyendiaye"}'::jsonb),
  (253, 'Izo Story', 'Macro-influenceur', 'Médias & Animateurs', '980K', 980000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '8.6%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@izostory","instagram":"https://instagram.com/izostory","facebook":"https://facebook.com"}'::jsonb),
  (254, 'Moustapha SN', 'Macro-influenceur', 'Humour & Comédie', '860K', 860000, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80', true, false, '7.7%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@moustaphasn","instagram":"https://instagram.com/moustaphasn","facebook":"https://facebook.com"}'::jsonb),
  (255, 'Cisko et ses amis', 'Macro-influenceur', 'Humour & Comédie', '750K', 750000, 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&auto=format&fit=crop&q=80', true, false, '9.5%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@ciskoetsesamis","instagram":"https://instagram.com/ciskoetsesamis","facebook":"https://facebook.com"}'::jsonb),
  (256, 'Pape Thioune', 'Macro-influenceur', 'Business & Éducation', '640K', 640000, 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=600&auto=format&fit=crop&q=80', true, false, '7.4%', 'Leader d''opinion et créateur(trice) de contenus inspirants alliant expertise, développement personnel et vision entrepreneuriale pour la jeunesse sénégalaise.', '{"tiktok":"https://tiktok.com/@papethioune","instagram":"https://instagram.com/papethioune","facebook":"https://facebook.com"}'::jsonb),
  (258, 'Khadeejaa', 'Macro-influenceur', 'Médias & Animateurs', '520K', 520000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@khadeejaa","instagram":"https://instagram.com/khadeejaa","facebook":"https://facebook.com"}'::jsonb),
  (259, 'khady_serie_babel', 'Macro-influenceur', 'Cinéma & Séries', '1.9M', 1900000, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Artiste et comédien(ne) d''exception, figure majeure du paysage audiovisuel et des séries phares sénégalaises. Très apprécié(e) pour son jeu d''acteur et sa forte proximité avec le public.', '{"tiktok":"https://tiktok.com/@khady_serie_babel","instagram":"https://instagram.com/khady_serie_babel","facebook":"https://facebook.com","youtube":"https://youtube.com/@khady_serie_babel"}'::jsonb),
  (260, 'MC KARA', 'Macro-influenceur', 'Humour & Comédie', '1.4M', 1400000, 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@mckara","instagram":"https://instagram.com/mckara","facebook":"https://facebook.com","youtube":"https://youtube.com/@mckara"}'::jsonb),
  (261, 'GORA SENE', 'Macro-influenceur', 'Lifestyle & Culture', '1.1M', 1100000, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@gorasene","instagram":"https://instagram.com/gorasene","facebook":"https://facebook.com","youtube":"https://youtube.com/@gorasene"}'::jsonb),
  (262, 'LADY PURPLE', 'Macro-influenceur', 'Mode & Beauté', '920K', 920000, 'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@ladypurple","instagram":"https://instagram.com/ladypurple","facebook":"https://facebook.com"}'::jsonb),
  (263, 'MOUSSA OFFICIEL', 'Macro-influenceur', 'Lifestyle & Culture', '810K', 810000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@moussaofficiel","instagram":"https://instagram.com/moussaofficiel","facebook":"https://facebook.com"}'::jsonb),
  (265, 'VOLETTE OFF', 'Macro-influenceur', 'Humour & Comédie', '640K', 640000, 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80', true, false, '7.4%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@voletteoff","instagram":"https://instagram.com/voletteoff","facebook":"https://facebook.com"}'::jsonb),
  (266, 'MIGNONNE LEBOU', 'Macro-influenceur', 'Médias & Animateurs', '540K', 540000, 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&auto=format&fit=crop&q=80', true, false, '8.3%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@mignonnelebou","instagram":"https://instagram.com/mignonnelebou","facebook":"https://facebook.com"}'::jsonb),
  (268, 'THE CLEANMAN', 'Macro-influenceur', 'Mode & Beauté', '1.9M', 1900000, 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@thecleanman","instagram":"https://instagram.com/thecleanman","facebook":"https://facebook.com","youtube":"https://youtube.com/@thecleanman"}'::jsonb),
  (269, 'SABS SY', 'Macro-influenceur', 'Humour & Comédie', '1.4M', 1400000, 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@sabssy","instagram":"https://instagram.com/sabssy","facebook":"https://facebook.com","youtube":"https://youtube.com/@sabssy"}'::jsonb),
  (270, 'BIRA', 'Macro-influenceur', 'Mode & Beauté', '1.1M', 1100000, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@bira","instagram":"https://instagram.com/bira","facebook":"https://facebook.com","youtube":"https://youtube.com/@bira"}'::jsonb),
  (271, 'BAMBA NIASE TV', 'Macro-influenceur', 'Médias & Animateurs', '920K', 920000, 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@bambaniasetv","instagram":"https://instagram.com/bambaniasetv","facebook":"https://facebook.com"}'::jsonb),
  (272, 'Chacha Eben', 'Macro-influenceur', 'Humour & Comédie', '810K', 810000, 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@chachaeben","instagram":"https://instagram.com/chachaeben","facebook":"https://facebook.com"}'::jsonb),
  (275, 'Poupeii_Kelly', 'Macro-influenceur', 'Lifestyle & Culture', '590K', 590000, 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@poupeii_kelly","instagram":"https://instagram.com/poupeii_kelly","facebook":"https://facebook.com"}'::jsonb),
  (276, 'MANSOUR DIOUF', 'Macro-influenceur', 'Médias & Animateurs', '520K', 520000, 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@mansourdiouf","instagram":"https://instagram.com/mansourdiouf","facebook":"https://facebook.com"}'::jsonb),
  (277, 'Mr Babacar', 'Macro-influenceur', 'Lifestyle & Culture', '1.9M', 1900000, 'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Créateur(trice) de contenus de référence (créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@mrbabacar","instagram":"https://instagram.com/mrbabacar","facebook":"https://facebook.com","youtube":"https://youtube.com/@mrbabacar"}'::jsonb),
  (280, 'Dash TV', 'Macro-influenceur', 'Médias & Animateurs', '1.1M', 1100000, 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@dashtv","instagram":"https://instagram.com/dashtv","facebook":"https://facebook.com","youtube":"https://youtube.com/@dashtv"}'::jsonb),
  (281, 'Khar D', 'Macro-influenceur', 'Mode & Beauté', '920K', 920000, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@khard","instagram":"https://instagram.com/khard","facebook":"https://facebook.com"}'::jsonb),
  (282, 'BY ZALLE', 'Macro-influenceur', 'Humour & Comédie', '810K', 810000, 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@byzalle","instagram":"https://instagram.com/byzalle","facebook":"https://facebook.com"}'::jsonb),
  (283, 'Munshineee', 'Macro-influenceur', 'Lifestyle & Culture', '690K', 690000, 'https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Créateur(trice) de contenus de référence (Créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@munshineee","instagram":"https://instagram.com/munshineee","facebook":"https://facebook.com"}'::jsonb),
  (285, 'SALLISTOH', 'Macro-influenceur', 'Lifestyle & Culture', '540K', 540000, 'https://images.unsplash.com/photo-1519764622345-23439dd774f7?w=600&auto=format&fit=crop&q=80', true, false, '8.3%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@sallistoh","instagram":"https://instagram.com/sallistoh","facebook":"https://facebook.com"}'::jsonb),
  (287, 'Hizbou', 'Macro-influenceur', 'Mode & Beauté', '1.9M', 1900000, 'https://images.unsplash.com/photo-1507152832244-10d45c7eda57?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@hizbou","instagram":"https://instagram.com/hizbou","facebook":"https://facebook.com","youtube":"https://youtube.com/@hizbou"}'::jsonb),
  (288, 'Bousso Thiam Baabel', 'Macro-influenceur', 'Cinéma & Séries', '1.4M', 1400000, 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Artiste et comédien(ne) d''exception, figure majeure du paysage audiovisuel et des séries phares sénégalaises. Très apprécié(e) pour son jeu d''acteur et sa forte proximité avec le public.', '{"tiktok":"https://tiktok.com/@boussothiambaabel","instagram":"https://instagram.com/boussothiambaabel","facebook":"https://facebook.com","youtube":"https://youtube.com/@boussothiambaabel"}'::jsonb),
  (290, 'Barry Rougui', 'Macro-influenceur', 'Humour & Comédie', '980K', 980000, 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=600&auto=format&fit=crop&q=80', true, false, '8.6%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@barryrougui","instagram":"https://instagram.com/barryrougui","facebook":"https://facebook.com"}'::jsonb),
  (291, 'MG MAKER', 'Macro-influenceur', 'Lifestyle & Culture', '860K', 860000, 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=600&auto=format&fit=crop&q=80', true, false, '7.7%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@mgmaker","instagram":"https://instagram.com/mgmaker","facebook":"https://facebook.com"}'::jsonb),
  (292, 'IBULAAY GIS TEXE', 'Macro-influenceur', 'Médias & Animateurs', '750K', 750000, 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=600&auto=format&fit=crop&q=80', true, false, '9.5%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@ibulaaygistexe","instagram":"https://instagram.com/ibulaaygistexe","facebook":"https://facebook.com"}'::jsonb),
  (294, 'Pogboss', 'Macro-influenceur', 'Humour & Comédie', '590K', 590000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, false, '10.1%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@pogboss","instagram":"https://instagram.com/pogboss","facebook":"https://facebook.com"}'::jsonb),
  (295, 'Ouzz Lefou', 'Macro-influenceur', 'Humour & Comédie', '520K', 520000, 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@ouzzlefou","instagram":"https://instagram.com/ouzzlefou","facebook":"https://facebook.com"}'::jsonb),
  (296, 'Tapha Faye', 'Macro-influenceur', 'Humour & Comédie', '1.9M', 1900000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, true, '8.9%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@taphafaye","instagram":"https://instagram.com/taphafaye","facebook":"https://facebook.com","youtube":"https://youtube.com/@taphafaye"}'::jsonb),
  (297, 'Fatayma & David', 'Macro-influenceur', 'Lifestyle & Culture', '1.4M', 1400000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, true, '8.4%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@fataymadavid","instagram":"https://instagram.com/fataymadavid","facebook":"https://facebook.com","youtube":"https://youtube.com/@fataymadavid"}'::jsonb),
  (298, 'Pispa Boks Takander', 'Macro-influenceur', 'Lifestyle & Culture', '1.1M', 1100000, 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Créateur(trice) de contenus de référence (créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@pispabokstakander","instagram":"https://instagram.com/pispabokstakander","facebook":"https://facebook.com","youtube":"https://youtube.com/@pispabokstakander"}'::jsonb),
  (299, 'BAYE ACTEUR', 'Macro-influenceur', 'Cinéma & Séries', '920K', 920000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Artiste et comédien(ne) d''exception, figure majeure du paysage audiovisuel et des séries phares sénégalaises. Très apprécié(e) pour son jeu d''acteur et sa forte proximité avec le public.', '{"tiktok":"https://tiktok.com/@bayeacteur","instagram":"https://instagram.com/bayeacteur","facebook":"https://facebook.com"}'::jsonb),
  (300, 'ALVINE_FOOTSTYLE', 'Macro-influenceur', 'Sport & Bien-être', '810K', 810000, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Passionné(e) de sport et de dynamique physique, inspire sa communauté à travers le dépassement de soi, l''énergie positive et les performances.', '{"tiktok":"https://tiktok.com/@alvine_footstyle","instagram":"https://instagram.com/alvine_footstyle","facebook":"https://facebook.com"}'::jsonb),
  (301, 'Mass Comédien', 'Macro-influenceur', 'Humour & Comédie', '690K', 690000, 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@masscomedien","instagram":"https://instagram.com/masscomedien","facebook":"https://facebook.com"}'::jsonb),
  (303, 'Barra Falilou', 'Macro-influenceur', 'Médias & Animateurs', '540K', 540000, 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=600&auto=format&fit=crop&q=80', true, false, '8.3%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@barrafalilou","instagram":"https://instagram.com/barrafalilou","facebook":"https://facebook.com"}'::jsonb),
  (304, 'Abdu_10011', 'Macro-influenceur', 'Lifestyle & Culture', '2.4M', 2400000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, true, '9.8%', 'Créateur(trice) de contenus de référence (Créateur de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@abdu_10011","instagram":"https://instagram.com/abdu_10011","facebook":"https://facebook.com","youtube":"https://youtube.com/@abdu_10011"}'::jsonb),
  (305, 'Jean Pierre Coly', 'Macro-influenceur', 'Humour & Comédie', '1.6M', 1600000, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80', true, true, '11.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@jeanpierrecoly","instagram":"https://instagram.com/jeanpierrecoly","facebook":"https://facebook.com","youtube":"https://youtube.com/@jeanpierrecoly"}'::jsonb),
  (308, 'Zo Oualy Tech', 'Macro-influenceur', 'Business & Éducation', '980K', 980000, 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&auto=format&fit=crop&q=80', true, false, '8.6%', 'Leader d''opinion et créateur(trice) de contenus inspirants alliant expertise, développement personnel et vision entrepreneuriale pour la jeunesse sénégalaise.', '{"tiktok":"https://tiktok.com/@zooualytech","instagram":"https://instagram.com/zooualytech","facebook":"https://facebook.com"}'::jsonb),
  (309, 'PML Lebou', 'Macro-influenceur', 'Médias & Animateurs', '860K', 860000, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80', true, false, '7.7%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@pmllebou","instagram":"https://instagram.com/pmllebou","facebook":"https://facebook.com"}'::jsonb),
  (310, 'Wagnuu Coumba', 'Macro-influenceur', 'Gastronomie & Cuisine', '750K', 750000, 'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=600&auto=format&fit=crop&q=80', true, false, '9.5%', 'Célébration des saveurs sénégalaises et de l''art culinaire moderne, partage des recettes authentiques et astuces gourmandes très suivies.', '{"tiktok":"https://tiktok.com/@wagnuucoumba","instagram":"https://instagram.com/wagnuucoumba","facebook":"https://facebook.com"}'::jsonb),
  (311, 'Mounnaaa', 'Macro-influenceur', 'Mode & Beauté', '640K', 640000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, false, '7.4%', 'Ambassadrice d''élégance et de tendances cosmétiques, suivie pour son sens aigu du style, du make-up et du lifestyle moderne à Dakar. Partenaire privilégié(e) des marques de mode.', '{"tiktok":"https://tiktok.com/@mounnaaa","instagram":"https://instagram.com/mounnaaa","facebook":"https://facebook.com"}'::jsonb),
  (312, 'Fifi série Baabel', 'Macro-influenceur', 'Cinéma & Séries', '540K', 540000, 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&auto=format&fit=crop&q=80', true, false, '8.3%', 'Artiste et comédien(ne) d''exception, figure majeure du paysage audiovisuel et des séries phares sénégalaises. Très apprécié(e) pour son jeu d''acteur et sa forte proximité avec le public.', '{"tiktok":"https://tiktok.com/@fifiseriebaabel","instagram":"https://instagram.com/fifiseriebaabel","facebook":"https://facebook.com"}'::jsonb),
  (313, 'Oumy Ganee', 'Macro-influenceur', 'Lifestyle & Culture', '2.4M', 2400000, 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=600&auto=format&fit=crop&q=80', true, true, '9.8%', 'Créateur(trice) de contenus de référence (créatrice de contenu), fédère une audience engagée et fidèle au Sénégal et à l''international pour des campagnes d''influence percutantes.', '{"tiktok":"https://tiktok.com/@oumyganee","instagram":"https://instagram.com/oumyganee","facebook":"https://facebook.com","youtube":"https://youtube.com/@oumyganee"}'::jsonb),
  (314, 'Bass Thiam', 'Macro-influenceur', 'Humour & Comédie', '1.6M', 1600000, 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80', true, true, '11.2%', 'Figure incontournable du rire et du divertissement digital au Sénégal. Ses sketchs, parodies et vidéos humoristiques cumulent des millions de vues à travers le pays et la diaspora.', '{"tiktok":"https://tiktok.com/@bassthiam","instagram":"https://instagram.com/bassthiam","facebook":"https://facebook.com","youtube":"https://youtube.com/@bassthiam"}'::jsonb),
  (316, 'The Real Aichad', 'Macro-influenceur', 'Médias & Animateurs', '1.1M', 1100000, 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Créateur(trice) d''impact et voix influente sur les plateformes numériques et médias. Maîtrise l''animation, le storytelling et le contact direct avec des centaines de milliers d''abonnés.', '{"tiktok":"https://tiktok.com/@therealaichad","instagram":"https://instagram.com/therealaichad","facebook":"https://facebook.com","youtube":"https://youtube.com/@therealaichad"}'::jsonb),
  (317, 'OMD_Vibes', 'Macro-influenceur', 'Musique & Danse', '920K', 920000, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80', true, false, '10.4%', 'Talent rythmé et créateur(trice) de vibes afro-urbaines incontournables. Rythme les tendances musicales et les challenges viraux sur TikTok et Instagram.', '{"tiktok":"https://tiktok.com/@omd_vibes","instagram":"https://instagram.com/omd_vibes","facebook":"https://facebook.com"}'::jsonb),
  (153, 'NANETTE', 'Micro-influenceur', 'Lifestyle & Famille', '280K', 280000, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Conseils du quotidien, famille, maternité et lifestyle bienveillant.', '{"tiktok":"https://tiktok.com/@nanette","instagram":"https://instagram.com/nanette"}'::jsonb),
  (151, 'Rokhaya', 'Micro-influenceur', 'Mode & Beauté', '340K', 340000, 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80', true, false, '6.9%', 'Inspirations tenues traditionnelles revisités, conseils skincare et astuces coiffure.', '{"tiktok":"https://tiktok.com/@rokhaya","instagram":"https://instagram.com/rokhaya"}'::jsonb),
  (144, 'Abdoul Wahab Dièye', 'Micro-influenceur', 'Business & Éducation', '190K', 190000, 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80', true, false, '6.4%', 'Expert entrepreneuriat, finance personnelle et conseils carrière pour la jeunesse africaine.', '{"tiktok":"https://tiktok.com/@abdoulwahabdiye","instagram":"https://instagram.com/abdoulwahabdiye"}'::jsonb),
  (138, 'Eva Loyalty', 'Micro-influenceur', 'Mode & Beauté', '370K', 370000, 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80', true, false, '7.7%', 'Make-up artist et créatrice visuelle axée sur la beauté noire et les cosmétiques de prestige.', '{"tiktok":"https://tiktok.com/@evaloyalty","instagram":"https://instagram.com/evaloyalty"}'::jsonb),
  (119, 'Mamadou Lamine CISSOKHO', 'Micro-influenceur', 'Business & Éducation', '230K', 230000, 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&auto=format&fit=crop&q=80', true, false, '7.0%', 'Consultant stratégie d''entreprise, formateur en leadership et conférencier en Afrique de l''Ouest.', '{"tiktok":"https://tiktok.com/@mamadoulaminecissokho","instagram":"https://instagram.com/mamadoulaminecissokho"}'::jsonb),
  (105, 'Diekk Sikim React', 'Micro-influenceur', 'Humour & Réaction', '380K', 380000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '9.3%', 'Réactions hilarantes aux actualités du net, revues de séries et analyses sans filtre.', '{"tiktok":"https://tiktok.com/@diekksikimreact","instagram":"https://instagram.com/diekksikimreact"}'::jsonb),
  (104, 'DIOUMA THIAM', 'Micro-influenceur', 'Mode & Beauté', '290K', 290000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, false, '8.2%', 'Créatrice de contenu bien-être, cosmétiques et élégance dakaroise.', '{"tiktok":"https://tiktok.com/@dioumathiam","instagram":"https://instagram.com/dioumathiam"}'::jsonb),
  (90, 'VERONIKA YAZBACK', 'Micro-influenceur', 'Lifestyle & Fitness', '410K', 410000, 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=600&auto=format&fit=crop&q=80', true, false, '7.1%', 'Coach de vie, bien-être, nutrition équilibrée et routines sportives motivantes.', '{"tiktok":"https://tiktok.com/@veronikayazback","instagram":"https://instagram.com/veronikayazback"}'::jsonb),
  (79, 'SAFIA DIATTA', 'Micro-influenceur', 'Mode & Beauté', '260K', 260000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '8.0%', 'Astuces coiffure nappy, cosmétiques bio et rituels de beauté africains.', '{"tiktok":"https://tiktok.com/@safiadiatta","instagram":"https://instagram.com/safiadiatta"}'::jsonb),
  (75, 'ZALLE YB L’OFFICIEL', 'Micro-influenceur', 'Humour & Comédie', '490K', 490000, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80', true, false, '9.0%', 'Sketchs viraux rythmés par l''actualité sénégalaise, parodies de footballeurs et de musiciens.', '{"tiktok":"https://tiktok.com/@zalleyblofficiel","instagram":"https://instagram.com/zalleyblofficiel"}'::jsonb),
  (73, 'CAROLE VALÉRIE ANDRADE', 'Micro-influenceur', 'Mode & Beauté', '350K', 350000, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Mannequin professionnel, défilés internationaux et shooting haute couture africaine.', '{"tiktok":"https://tiktok.com/@carolevalrieandrade","instagram":"https://instagram.com/carolevalrieandrade"}'::jsonb),
  (65, 'MISS AICHA', 'Micro-influenceur', 'Lifestyle & Famille', '270K', 270000, 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=80', true, false, '7.8%', 'Partages chaleureux autour du quotidien, astuces bien-être et maternité.', '{"tiktok":"https://tiktok.com/@missaicha","instagram":"https://instagram.com/missaicha"}'::jsonb),
  (63, 'BLACK FATWA', 'Micro-influenceur', 'Humour & Parodie', '430K', 430000, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80', true, false, '8.7%', 'Vidéos de stand-up digital, anecdotes désopilantes et chroniques humoristiques.', '{"tiktok":"https://tiktok.com/@blackfatwa","instagram":"https://instagram.com/blackfatwa"}'::jsonb),
  (56, 'DIEY', 'Micro-influenceur', 'Mode & Beauté', '240K', 240000, 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Blogueuse mode, tutoriels accessoires et valorisation des créateurs locaux sénégalais.', '{"tiktok":"https://tiktok.com/@diey","instagram":"https://instagram.com/diey"}'::jsonb),
  (52, 'Edu NDAO', 'Micro-influenceur', 'Musique & Culture', '310K', 310000, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80', true, false, '7.2%', 'Chroniqueur musical, découvertes de jeunes talents sénégalais et couverture de festivals.', '{"tiktok":"https://tiktok.com/@edundao","instagram":"https://instagram.com/edundao"}'::jsonb),
  (45, 'OULY', 'Micro-influenceur', 'Mode & Beauté', '350K', 350000, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&auto=format&fit=crop&q=80', true, false, '7.6%', 'Tutoriels makeup, routines capillaires et collaborations beauté.', '{"tiktok":"https://tiktok.com/@ouly","instagram":"https://instagram.com/ouly"}'::jsonb),
  (44, 'Bathie Drezzy', 'Micro-influenceur', 'Humour & Divertissement', '460K', 460000, 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=80', true, false, '8.8%', 'Challenges TikTok, micro-trottoirs et vidéos divertissantes à Dakar.', '{"tiktok":"https://tiktok.com/@bathiedrezzy","instagram":"https://instagram.com/bathiedrezzy"}'::jsonb),
  (43, 'SEYDINA', 'Micro-influenceur', 'Humour & Comédie', '380K', 380000, 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=80', true, false, '8.1%', 'Sketches courts inspirés de la vie familiale et des relations de couple.', '{"tiktok":"https://tiktok.com/@seydina","instagram":"https://instagram.com/seydina"}'::jsonb),
  (35, 'Maty Smith', 'Micro-influenceur', 'Lifestyle & Voyage', '280K', 280000, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80', true, false, '7.5%', 'Carnets de voyage en Afrique, hôtels et recommandations culinaires.', '{"tiktok":"https://tiktok.com/@matysmith","instagram":"https://instagram.com/matysmith"}'::jsonb),
  (22, 'Paco Kome', 'Micro-influenceur', 'Humour & Comédie', '350K', 350000, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80', true, false, '8.6%', 'Comédie absurde et parodies de trends viraux sur les réseaux sociaux.', '{"tiktok":"https://tiktok.com/@pacokome","instagram":"https://instagram.com/pacokome"}'::jsonb),
  (21, 'Dou King', 'Micro-influenceur', 'Musique & Danse', '420K', 420000, 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=80', true, false, '7.8%', 'Chorégraphe de street dance et créateur de challenges danse afro.', '{"tiktok":"https://tiktok.com/@douking","instagram":"https://instagram.com/douking"}'::jsonb),
  (20, 'Lasga Ndiaye', 'Micro-influenceur', 'Lifestyle & Culture', '290K', 290000, 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&auto=format&fit=crop&q=80', true, false, '7.0%', 'Photographe urbain et documentariste de la jeunesse dakaroise.', '{"tiktok":"https://tiktok.com/@lasgandiaye","instagram":"https://instagram.com/lasgandiaye"}'::jsonb),
  (5, 'Pape Gora Sarr', 'Micro-influenceur', 'Sport & Médias', '390K', 390000, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80', true, false, '7.9%', 'Journaliste sportif, expert football local et international, commentateur très suivi.', '{"tiktok":"https://tiktok.com/@papegorasarr","instagram":"https://instagram.com/papegorasarr"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  niche = EXCLUDED.niche,
  followers = EXCLUDED.followers,
  followers_count = EXCLUDED.followers_count,
  photo = EXCLUDED.photo,
  verified = EXCLUDED.verified,
  featured = EXCLUDED.featured,
  engagement_rate = EXCLUDED.engagement_rate,
  bio = EXCLUDED.bio,
  socials = EXCLUDED.socials;
